name: Auto format pull requests

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 20

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper # The version is located in gradle/wrapper/gradle-wrapper.properties

      - name: Run format
        run: gradle spotlessApply

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply spotless formatting"
